apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: dev
spec:
  containers:
    - image: nginx:latest
      name: pod
      ports:
        - name: nginx-port
          containerPort: 80
          protocol: TCP
      startupProbe:
#        httpGet:
#          path: /index.html
#          port: 80
#        tcpSocket:
#          port: 80
        exec:
          command:
            - cat
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5